# Generated by Django 4.2.7 on 2024-08-05 12:46

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import smart_selects.db_fields
import taqqos.document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0004_alter_file_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='название uzb')),
                ('name_ru', models.CharField(max_length=200, verbose_name='название rus')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='код')),
                ('type', models.CharField(choices=[('text', 'text'), ('toggle', 'toggle'), ('option', 'option'), ('multi_option', 'multi_option')], max_length=64, verbose_name='тип')),
                ('is_required', models.BooleanField(default=False, verbose_name='требуется')),
                ('order_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер')),
            ],
            options={
                'verbose_name': 'атрибут',
                'verbose_name_plural': 'атрибуты',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='название uzb')),
                ('name_ru', models.CharField(max_length=200, verbose_name='название rus')),
                ('order_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.brand', verbose_name='родитель')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='название uzb')),
                ('name_ru', models.CharField(max_length=200, verbose_name='название rus')),
                ('order_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('brands', mptt.fields.TreeManyToManyField(blank=True, related_name='categories', to='product.brand', verbose_name='бренды')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.file')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='родитель')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='название uzb')),
                ('name_ru', models.CharField(max_length=200, verbose_name='название rus')),
                ('code', models.CharField(max_length=64, verbose_name='код')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('order_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.attribute', verbose_name='атрибут')),
            ],
            options={
                'verbose_name': 'параметр',
                'verbose_name_plural': 'параметры',
                'unique_together': {('attribute', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата редактирования')),
                ('name_uz', models.CharField(max_length=200, verbose_name='название uzb')),
                ('name_ru', models.CharField(max_length=200, verbose_name='название rus')),
                ('slug', models.SlugField(unique=True)),
                ('short_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='название короткое')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=taqqos.document.models.upload_name, verbose_name='фото')),
                ('is_popular', models.BooleanField(default=False, verbose_name='популярен')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='описание uzb')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='описание rus')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.brand', verbose_name='бренд')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата редактирования')),
                ('rate', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='ставка')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product', verbose_name='продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.file', verbose_name='фото')),
                ('image_mobile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders_mobile', to='document.file', verbose_name='фото для мобиль')),
            ],
            options={
                'verbose_name': 'Слидер',
                'verbose_name_plural': 'Слидеры',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.file', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Продавц',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='ReviewFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата редактирования')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.file', verbose_name='файл')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_files', to='product.review', verbose_name='отзыв')),
            ],
            options={
                'verbose_name': 'отзыв файл',
                'verbose_name_plural': 'отзыв файлы',
            },
        ),
        migrations.CreateModel(
            name='ProductVideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='URL-адрес')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reviews', to='product.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'видеообзор',
                'verbose_name_plural': 'видеообзоры',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=taqqos.document.models.upload_name, verbose_name='фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'фото продукта',
                'verbose_name_plural': 'фотографии продукта',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='название uzb')),
                ('name_ru', models.CharField(max_length=200, verbose_name='название rus')),
                ('value', models.CharField(max_length=512, verbose_name='ценить')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'продукт характеристика',
                'verbose_name_plural': 'продукт характеристики',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute', verbose_name='атрибут')),
                ('option', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='attribute', chained_model_field='attribute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_attributes', to='product.option')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'продукт атрибут',
                'verbose_name_plural': 'продукт атрибуты',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='categories',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='attributes', to='product.category', verbose_name='категории'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата редактирования')),
                ('name', models.CharField(max_length=512, verbose_name='название')),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='сумма цены')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('features', models.JSONField(blank=True, null=True, verbose_name='характеристика')),
                ('has_credit', models.BooleanField(default=False, verbose_name='есть кредит')),
                ('credit_monthly_amount', models.CharField(blank=True, max_length=150, null=True, verbose_name='ежемесячная сумма кредита')),
                ('has_delivery', models.BooleanField(default=False, verbose_name='есть доставка')),
                ('delivery_info', models.TextField(blank=True, null=True, verbose_name='информация о доставке')),
                ('address', models.TextField(blank=True, null=True, verbose_name='адрес')),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='номер телефона')),
                ('website', models.CharField(max_length=256, verbose_name='Веб-сайт')),
                ('website_link', models.URLField(blank=True, null=True, verbose_name='ссылка на сайт')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.file', verbose_name='фото')),
                ('products', models.ManyToManyField(blank=True, related_name='product_prices', to='product.product', verbose_name='продукты')),
            ],
            options={
                'verbose_name': 'цены на продукцию',
                'verbose_name_plural': 'цены на продукцию',
                'unique_together': {('name', 'website')},
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата редактирования')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='product.product', verbose_name='продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Избранной',
                'verbose_name_plural': 'Избранное',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
