# Generated by Django 4.2.7 on 2024-08-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image url'),
        ),
    ]
