# Generated by Django 4.2.7 on 2023-12-18 07:42

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='brands',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='categories', to='product.brand', verbose_name='бренды'),
        ),
    ]
