# Generated by Django 4.2.7 on 2023-11-26 06:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='описание uzb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='описание rus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='название uzb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='название rus'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductTranslation',
        ),
    ]
