# Generated by Django 4.2.7 on 2023-12-22 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('product', '0003_alter_category_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.file', verbose_name='фото'),
        ),
    ]
