# Generated by Django 4.2.7 on 2023-12-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_brands_delete_categorybrand'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brandtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='brandtranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='optiontranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='optiontranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='productfeaturetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productfeaturetranslation',
            name='master',
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='название uzb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='название rus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='название uzb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='name_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='название rus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='название uzb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='название rus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='name_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='название uzb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='name_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='название rus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfeature',
            name='name_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='название uzb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfeature',
            name='name_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='название rus'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AttributeTranslation',
        ),
        migrations.DeleteModel(
            name='BrandTranslation',
        ),
        migrations.DeleteModel(
            name='CategoryTranslation',
        ),
        migrations.DeleteModel(
            name='OptionTranslation',
        ),
        migrations.DeleteModel(
            name='ProductFeatureTranslation',
        ),
    ]
