# Generated by Django 4.2.7 on 2023-12-30 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('product', '0004_productprice_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=256, null=True, verbose_name='название uzb')),
                ('name_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='название rus')),
                ('text_uz', models.TextField(blank=True, null=True, verbose_name='текст uzb')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='текст rus')),
            ],
            options={
                'verbose_name': 'Слидер',
                'verbose_name_plural': 'Слидеры',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.file', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Продавц',
                'verbose_name_plural': 'Продавцы',
            },
        ),
    ]
