# Generated by Django 4.2.7 on 2023-12-30 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('product', '0005_slider_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.file', verbose_name='фото'),
        ),
    ]
