# Generated by Django 4.2.7 on 2023-12-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер'),
        ),
        migrations.AddField(
            model_name='slider',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер'),
        ),
    ]
