# Generated by Django 4.2.7 on 2023-12-07 09:58

import ckeditor_uploader.fields
from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_brand_level_brand_lft_brand_rght_brand_tree_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name_ru',
            field=models.CharField(max_length=200, verbose_name='название rus'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_uz',
            field=models.CharField(max_length=200, verbose_name='название uzb'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(max_length=200, verbose_name='название rus'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_uz',
            field=models.CharField(max_length=200, verbose_name='название uzb'),
        ),
        migrations.AlterField(
            model_name='category',
            name='brands',
            field=mptt.fields.TreeManyToManyField(related_name='categories', to='product.brand'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=200, verbose_name='название rus'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=200, verbose_name='название uzb'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name_ru',
            field=models.CharField(max_length=200, verbose_name='название rus'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name_uz',
            field=models.CharField(max_length=200, verbose_name='название uzb'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='описание rus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='описание uzb'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=200, verbose_name='название rus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=200, verbose_name='название uzb'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name_ru',
            field=models.CharField(max_length=200, verbose_name='название rus'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name_uz',
            field=models.CharField(max_length=200, verbose_name='название uzb'),
        ),
    ]
