# Generated by Django 4.2.7 on 2024-01-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('product', '0007_seller_order_number_slider_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='text_uz',
        ),
        migrations.AddField(
            model_name='slider',
            name='image_mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders_mobile', to='document.file', verbose_name='фото для мобиль'),
        ),
    ]
