# Generated by Django 4.2.7 on 2023-12-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_attribute_name_ru_alter_attribute_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='порядковый номер'),
        ),
    ]
