# Generated by Django 4.2.7 on 2023-12-11 07:55

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_brand_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='categories',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='attributes', to='product.category', verbose_name='categories'),
        ),
    ]
