# Generated by Django 4.2.7 on 2023-12-11 07:57

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_attribute_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='categories',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='attributes', to='product.category', verbose_name='категории'),
        ),
    ]
