# Generated by Django 4.2.7 on 2024-01-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_productattribute_text_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='options',
            new_name='option',
        ),
    ]
