# Generated by Django 4.2.7 on 2024-01-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_options_productattribute_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='can_join',
        ),
        migrations.AddField(
            model_name='option',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='code',
            field=models.CharField(max_length=64, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='требуется'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('attribute', 'code')},
        ),
        migrations.RemoveField(
            model_name='option',
            name='label',
        ),
    ]
