# Generated by Django 4.2.7 on 2024-01-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_attribute_can_join_option_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='сумма цены'),
        ),
    ]
