# Generated by Django 4.2.7 on 2023-12-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_brand_parent_alter_category_brands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата редактирования'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата редактирования'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата редактирования'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата редактирования'),
        ),
        migrations.AlterField(
            model_name='reviewfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reviewfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата редактирования'),
        ),
    ]
