# Generated by Django 4.2.7 on 2024-01-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productprice_price_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('name', 'website')},
        ),
    ]
