# Generated by Django 4.2.7 on 2024-01-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_productprice_product_productprice_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='feature',
        ),
        migrations.AddField(
            model_name='productprice',
            name='features',
            field=models.JSONField(blank=True, null=True, verbose_name='характеристика'),
        ),
    ]
