# Generated by Django 4.2.7 on 2024-04-08 22:32

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_productattribute_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='option',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='attribute', chained_model_field='attribute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_attributes', show_all=True, to='product.option'),
        ),
    ]
