# Generated by Django 4.2.7 on 2023-11-24 07:17

from django.db import migrations, models
import taqqos.document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to=taqqos.document.models.upload_name)),
                ('file_type', models.CharField(blank=True, choices=[('video', 'video'), ('document', 'document'), ('image', 'image')], max_length=30, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=taqqos.document.models.upload_name)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
