# Generated by Django 4.2.7 on 2023-12-11 11:38

from django.db import migrations, models
import taqqos.document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'файл', 'verbose_name_plural': 'файлы'},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=taqqos.document.models.upload_name, verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, choices=[('video', 'video'), ('document', 'document'), ('image', 'image')], max_length=30, null=True, verbose_name='тип файла'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название'),
        ),
    ]
