# Generated by Django 4.2.7 on 2024-04-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
