# Generated by Django 4.2.7 on 2023-12-11 11:11

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_sms_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата присоединения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='fполное имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='активный'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='это демо'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='статус персонала'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, unique=True, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sms_code',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='смс-код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sms_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='смс свидание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='имя пользователя'),
        ),
    ]
