# Generated by Django 4.2.7 on 2023-12-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='полное имя'),
        ),
    ]
