# Generated by Django 4.2.7 on 2024-04-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districttranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='regiontranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
