# Generated by Django 4.2.7 on 2023-12-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'район', 'verbose_name_plural': 'районы'},
        ),
        migrations.AlterModelOptions(
            name='districttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'район Translation'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'регион', 'verbose_name_plural': 'регионы'},
        ),
        migrations.AlterModelOptions(
            name='regiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'регион Translation'},
        ),
    ]
